account_id = "d152562b703e05079d3ba29c0bb1662e"
name = "read-rpc"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[vars]
LATEST_TTL = "3"
HISTORICAL_TTL = "30"

routes = [
  { pattern = "readrpc.dread.cat", custom_domain = true }
]
